// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4L0V2AWIVZf3boSVbs7wtntarxnz3wkA',
    appId: '1:22192643386:android:a2cb0fcb51d42dea7b8403',
    messagingSenderId: '22192643386',
    projectId: 'social-media-platform-97945',
    storageBucket: 'social-media-platform-97945.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6okUjvrGLGBkbh2AJ_dOs-yXqGD3SngU',
    appId: '1:22192643386:ios:12534e43a6018be07b8403',
    messagingSenderId: '22192643386',
    projectId: 'social-media-platform-97945',
    storageBucket: 'social-media-platform-97945.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6okUjvrGLGBkbh2AJ_dOs-yXqGD3SngU',
    appId: '1:22192643386:ios:12534e43a6018be07b8403',
    messagingSenderId: '22192643386',
    projectId: 'social-media-platform-97945',
    storageBucket: 'social-media-platform-97945.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfvIPY_tGBXKDhSCJSfmaF3WRHsMqQwco',
    appId: '1:22192643386:web:ffb85fffd23c9c377b8403',
    messagingSenderId: '22192643386',
    projectId: 'social-media-platform-97945',
    authDomain: 'social-media-platform-97945.firebaseapp.com',
    storageBucket: 'social-media-platform-97945.appspot.com',
    measurementId: 'G-T3DY24CNZE',
  );
}
